name: Build CYD-2432S028 Release

on:
  push:
    branches:
      - main
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build_cyd_2432s028:
    name: Build CYD-2432S028
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: setup_python
        name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          pip install requests esptool platformio

      - name: Configure Build
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            version=${{ github.ref_name }}
          else
            version="${GITHUB_SHA::7}"
          fi

          sed -i "s/-DBRUCE_VERSION=/-DBRUCE_VERSION='\"$version\"' ; /g" ./platformio.ini
          sed -i "s/-DGIT_COMMIT_HASH='\"Homebrew\"'/\!echo '-DGIT_COMMIT_HASH=\\\\\\\\\"'\$\(git describe --always --dirty)'\\\\\\\\\"'/g" ./platformio.ini

      - name: Build Firmware
        run: |
          platformio run -e CYD-2432S028

      - name: Merge Binary Files
        run: |
          esptool.py --chip esp32 merge_bin -o Bruce-CYD-2432S028.bin \
            0x1000 .pio/build/CYD-2432S028/bootloader.bin \
            0x8000 .pio/build/CYD-2432S028/partitions.bin \
            0x10000 .pio/build/CYD-2432S028/firmware.bin

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Bruce-CYD-2432S028
          path: |
            Bruce-CYD-2432S028.bin
            .pio/build/CYD-2432S028/*.json
          retention-days: 5
